import { WordClue } from "./crosswordGen";

export interface CrosswordTheme {
  id: string;
  title: string;
  category: string;
  words: WordClue[];
}

export const CROSSWORD_THEMES: CrosswordTheme[] = [
  {
    id: "morning",
    title: "Morning Routine",
    category: "food",
    words: [
      { word: "TOAST", clue: "Breakfast slice, often buttered" },
      { word: "ALARM", clue: "Wakes you up, rudely" },
      { word: "MUG", clue: "Holds your coffee" },
      { word: "SUNRISE", clue: "Dawn's arrival" },
      { word: "STRETCH", clue: "Do this before getting out of bed" },
      { word: "SHOWER", clue: "Morning rinse" },
      { word: "ROUTE", clue: "Your path to work" },
      { word: "TEA", clue: "Kettle's usual purpose" },
      { word: "YAWN", clue: "Involuntary morning gesture" },
      { word: "RISE", clue: "Get up, as the sun does" },
    ],
  },
  {
    id: "ocean",
    title: "By the Sea",
    category: "nature",
    words: [
      { word: "WAVE", clue: "Rolls onto the shore" },
      { word: "SHELL", clue: "Home for a hermit crab" },
      { word: "TIDE", clue: "Rises and falls twice daily" },
      { word: "CORAL", clue: "Builds colorful reefs" },
      { word: "ANCHOR", clue: "Keeps a boat in place" },
      { word: "SAND", clue: "Beach's main ingredient" },
      { word: "CRAB", clue: "Walks sideways" },
      { word: "PIER", clue: "Walkway out over the water" },
      { word: "SALT", clue: "Makes the sea taste the way it does" },
      { word: "GULL", clue: "Beach bird known for stealing chips" },
    ],
  },
  {
    id: "kitchen",
    title: "In the Kitchen",
    category: "food",
    words: [
      { word: "WHISK", clue: "For beating eggs" },
      { word: "OVEN", clue: "Bakes your bread" },
      { word: "SPICE", clue: "Cinnamon or cumin, for one" },
      { word: "LADLE", clue: "Serves the soup" },
      { word: "KNIFE", clue: "Chops the vegetables" },
      { word: "SIMMER", clue: "Gentle cooking heat, below a boil" },
      { word: "TOAST", clue: "Browns bread in a toaster" },
      { word: "APRON", clue: "Protects your clothes while cooking" },
      { word: "STIR", clue: "Move a spoon around a pot" },
      { word: "PAN", clue: "Frying vessel" },
    ],
  },
  {
    id: "garden",
    title: "In the Garden",
    category: "nature",
    words: [
      { word: "ROSE", clue: "Thorny, fragrant flower" },
      { word: "SOIL", clue: "What roots grow in" },
      { word: "SPADE", clue: "Digs a hole" },
      { word: "SEED", clue: "Grows into a plant" },
      { word: "PETAL", clue: "Part of a flower" },
      { word: "BLOOM", clue: "To flower" },
      { word: "SHADE", clue: "Where ferns prefer to grow" },
      { word: "WATER", clue: "Plants need this to grow" },
      { word: "LEAF", clue: "Green part of a plant" },
      { word: "VINE", clue: "Climbing plant" },
    ],
  },
  {
    id: "music",
    title: "A Little Music",
    category: "music",
    words: [
      { word: "PIANO", clue: "88 keys, black and white" },
      { word: "TEMPO", clue: "Speed of a piece of music" },
      { word: "CHORD", clue: "Three or more notes together" },
      { word: "VIOLIN", clue: "Bowed string instrument" },
      { word: "SONG", clue: "A tune with words" },
      { word: "NOTE", clue: "A single musical sound" },
      { word: "DRUM", clue: "You hit this to keep the beat" },
      { word: "STAGE", clue: "Where performers stand" },
      { word: "RHYTHM", clue: "The music's pulse" },
      { word: "ENCORE", clue: "Audience shout for one more song" },
    ],
  },
  {
    id: "weather",
    title: "Weather Watch",
    category: "nature",
    words: [
      { word: "CLOUD", clue: "Floats in the sky, holds rain" },
      { word: "STORM", clue: "Thunder and lightning event" },
      { word: "BREEZE", clue: "A gentle wind" },
      { word: "FROST", clue: "Thin ice on the morning grass" },
      { word: "RAINBOW", clue: "Arc of color after rain" },
      { word: "MIST", clue: "Light, low-lying fog" },
      { word: "SNOW", clue: "Falls in soft white flakes" },
      { word: "HUMID", clue: "Sticky, moisture-heavy air" },
      { word: "SUNNY", clue: "Clear-sky weather" },
      { word: "GALE", clue: "A very strong wind" },
    ],
  },
  {
    id: "travel",
    title: "Getting Away",
    category: "travel",
    words: [
      { word: "TICKET", clue: "You need one to board" },
      { word: "MAP", clue: "Helps you find your way" },
      { word: "TRAIN", clue: "Rides on rails" },
      { word: "HOSTEL", clue: "Budget place to sleep" },
      { word: "PASSPORT", clue: "Your ID for crossing borders" },
      { word: "LUGGAGE", clue: "What you pack and haul around" },
      { word: "TRAIL", clue: "Path through the woods" },
      { word: "GUIDE", clue: "Leads a tour" },
      { word: "COMPASS", clue: "Always points north" },
      { word: "VISA", clue: "Permission to enter a country" },
    ],
  },
  {
    id: "reading",
    title: "Bookish",
    category: "books",
    words: [
      { word: "NOVEL", clue: "A long work of fiction" },
      { word: "CHAPTER", clue: "A section of a book" },
      { word: "PLOT", clue: "What happens in a story" },
      { word: "AUTHOR", clue: "Wrote the book" },
      { word: "SPINE", clue: "The book's backbone on the shelf" },
      { word: "VERSE", clue: "A line of poetry" },
      { word: "PAGE", clue: "One side of a leaf in a book" },
      { word: "LIBRARY", clue: "Full of borrowed books" },
      { word: "MARGIN", clue: "Where you scribble notes" },
      { word: "READER", clue: "Someone turning these very pages" },
    ],
  },
  {
    id: "sports",
    title: "Game Day",
    category: "sports",
    words: [
      { word: "GOAL", clue: "What a striker is aiming for" },
      { word: "COURT", clue: "Where basketball is played" },
      { word: "REFEREE", clue: "Blows the whistle" },
      { word: "SERVE", clue: "Starts a point in tennis" },
      { word: "MEDAL", clue: "Podium reward" },
      { word: "SPRINT", clue: "A short, fast race" },
      { word: "COACH", clue: "Trains the team" },
      { word: "STADIUM", clue: "Where the crowd gathers" },
      { word: "RACKET", clue: "Swung in tennis or badminton" },
      { word: "JERSEY", clue: "Team shirt with a number" },
    ],
  },
  {
    id: "museum",
    title: "At the Museum",
    category: "art",
    words: [
      { word: "CANVAS", clue: "What a painter paints on" },
      { word: "SKETCH", clue: "A quick, rough drawing" },
      { word: "EASEL", clue: "Holds the canvas upright" },
      { word: "GALLERY", clue: "Room full of art" },
      { word: "PALETTE", clue: "Where paint colors are mixed" },
      { word: "FRESCO", clue: "Painted straight onto wet plaster" },
      { word: "SCULPTOR", clue: "Carves or molds a statue" },
      { word: "MURAL", clue: "A painting on a wall" },
      { word: "HUE", clue: "Another word for a color" },
      { word: "FRAME", clue: "Borders a painting" },
    ],
  },
  {
    id: "nightsky",
    title: "Night Sky",
    category: "science",
    words: [
      { word: "COMET", clue: "Icy visitor with a tail" },
      { word: "ORBIT", clue: "A planet's path around the sun" },
      { word: "GALAXY", clue: "A vast collection of stars" },
      { word: "TELESCOPE", clue: "Brings distant stars closer" },
      { word: "ECLIPSE", clue: "When one body blocks another's light" },
      { word: "NEBULA", clue: "A cloud of gas and dust in space" },
      { word: "METEOR", clue: "A shooting star" },
      { word: "LUNAR", clue: "Relating to the moon" },
      { word: "ASTEROID", clue: "A rocky body orbiting the sun" },
      { word: "GRAVITY", clue: "Keeps your feet on the ground" },
    ],
  },
  {
    id: "mountains",
    title: "High Ground",
    category: "nature",
    words: [
      { word: "SUMMIT", clue: "The very top of a peak" },
      { word: "RIDGE", clue: "A long, narrow mountain crest" },
      { word: "GLACIER", clue: "A slow-moving river of ice" },
      { word: "ALTITUDE", clue: "Height above sea level" },
      { word: "TRAIL", clue: "The path you hike up" },
      { word: "PEAK", clue: "Another word for a mountain's top" },
      { word: "BOULDER", clue: "A large loose rock" },
      { word: "SLOPE", clue: "The mountain's angled side" },
      { word: "ECHO", clue: "What comes back when you shout in a valley" },
      { word: "CLIFF", clue: "A steep rock face" },
    ],
  },
  {
    id: "cinema",
    title: "At the Movies",
    category: "film",
    words: [
      { word: "SCREEN", clue: "Where the picture is projected" },
      { word: "DIRECTOR", clue: "Calls the shots on set" },
      { word: "SCRIPT", clue: "The written dialogue and story" },
      { word: "TRAILER", clue: "A short preview of what's coming" },
      { word: "SEQUEL", clue: "Part two of the story" },
      { word: "CAMEO", clue: "A brief, notable appearance" },
      { word: "POPCORN", clue: "The classic theater snack" },
      { word: "CREDITS", clue: "Rolls at the very end" },
      { word: "PLOT", clue: "What actually happens in the story" },
      { word: "ACTOR", clue: "Plays a role on screen" },
    ],
  },
  {
    id: "bakery",
    title: "At the Bakery",
    category: "food",
    words: [
      { word: "DOUGH", clue: "What you knead before it bakes" },
      { word: "YEAST", clue: "Makes bread rise" },
      { word: "CRUST", clue: "The bread's outer layer" },
      { word: "FLOUR", clue: "Bakery's most basic ingredient" },
      { word: "OVEN", clue: "Where the baking happens" },
      { word: "ICING", clue: "Sweet topping on a cake" },
      { word: "LOAF", clue: "A whole baked bread, uncut" },
      { word: "PASTRY", clue: "Flaky baked good, often filled" },
      { word: "RECIPE", clue: "Instructions for a dish" },
      { word: "KNEAD", clue: "Work the dough by hand" },
    ],
  },
  {
    id: "mindscape",
    title: "A Wandering Mind",
    category: "philosophy",
    words: [
      { word: "REASON", clue: "Logical thinking, roughly" },
      { word: "DOUBT", clue: "The opposite of certainty" },
      { word: "ETHICS", clue: "The study of right and wrong" },
      { word: "MEANING", clue: "What you're searching for, existentially" },
      { word: "IDEA", clue: "A single thought, distilled" },
      { word: "LOGIC", clue: "Step-by-step reasoning" },
      { word: "TRUTH", clue: "What philosophers argue endlessly about" },
      { word: "MIND", clue: "Where thoughts happen" },
      { word: "VALUE", clue: "What you believe matters" },
      { word: "SELF", clue: "The \"who\" behind your thoughts" },
    ],
  },
  {
    id: "festival",
    title: "Festival Lights",
    category: "indian_culture",
    words: [
      { word: "LANTERN", clue: "Lit and hung to mark a celebration" },
      { word: "SWEETS", clue: "Shared generously during a festival" },
      { word: "RANGOLI", clue: "Colorful floor pattern made for celebrations" },
      { word: "DIYA", clue: "A small oil lamp" },
      { word: "MEHNDI", clue: "Henna design on the hands" },
      { word: "DRUM", clue: "Instrument that leads a festival procession" },
      { word: "FEAST", clue: "A large shared celebratory meal" },
      { word: "GUEST", clue: "Someone you welcome for the occasion" },
      { word: "DANCE", clue: "What the courtyard fills with, come evening" },
      { word: "COLOR", clue: "Thrown, worn, or painted to celebrate" },
    ],
  },
  {
    id: "globaltable",
    title: "Around the Table",
    category: "world_culture",
    words: [
      { word: "SPICE", clue: "What travels furthest in a suitcase, smell-wise" },
      { word: "NOODLE", clue: "Long strand, many countries claim a version" },
      { word: "MARKET", clue: "Where the day's ingredients get chosen" },
      { word: "CUSTOM", clue: "A tradition passed down, unwritten" },
      { word: "FEAST", clue: "A meal that takes all day to make" },
      { word: "RECIPE", clue: "A grandmother's, usually undocumented" },
      { word: "TEA", clue: "Ritual drink, wildly different by country" },
      { word: "SPOON", clue: "Not every culture eats with one" },
      { word: "TOAST", clue: "What you raise before a shared meal" },
      { word: "GUEST", clue: "Treated as an honor to host" },
    ],
  },
  {
    id: "camera",
    title: "Through the Lens",
    category: "art",
    words: [
      { word: "SHUTTER", clue: "Opens and closes to let light in" },
      { word: "FOCUS", clue: "Sharpens the image" },
      { word: "APERTURE", clue: "Controls how much light enters" },
      { word: "EXPOSURE", clue: "How long the film or sensor is lit" },
      { word: "FRAME", clue: "What's included in the shot" },
      { word: "LENS", clue: "Bends the light into an image" },
      { word: "FILM", clue: "The old way of capturing light" },
      { word: "ZOOM", clue: "Get closer without moving your feet" },
      { word: "FLASH", clue: "A burst of extra light" },
      { word: "PRINT", clue: "The photo, made physical" },
    ],
  },
  {
    id: "forestwalk",
    title: "Into the Woods",
    category: "nature",
    words: [
      { word: "CANOPY", clue: "The forest's leafy ceiling" },
      { word: "MOSS", clue: "Soft green growth on old bark" },
      { word: "TRUNK", clue: "A tree's main stem" },
      { word: "FERN", clue: "Feathery plant that loves shade" },
      { word: "TRAIL", clue: "The path through the trees" },
      { word: "ROOTS", clue: "Anchor a tree underground" },
      { word: "BARK", clue: "A tree's outer skin" },
      { word: "CLEARING", clue: "A sudden open patch of light" },
      { word: "ACORN", clue: "An oak tree's seed" },
      { word: "OWL", clue: "The forest's night-shift hunter" },
    ],
  },
  {
    id: "rainyday",
    title: "Rainy Day",
    category: "nature",
    words: [
      { word: "PUDDLE", clue: "Small pool left behind by rain" },
      { word: "UMBRELLA", clue: "Keeps you dry, mostly" },
      { word: "DRIZZLE", clue: "Light, gentle rain" },
      { word: "THUNDER", clue: "The sound that follows lightning" },
      { word: "DOWNPOUR", clue: "Rain that means business" },
      { word: "RAINCOAT", clue: "Waterproof jacket for the occasion" },
      { word: "GUTTER", clue: "Channels rainwater off a roof" },
      { word: "SPLASH", clue: "What a puddle does underfoot" },
      { word: "DAMP", clue: "Not quite dry" },
      { word: "STORM", clue: "Rain with attitude" },
    ],
  },
  {
    id: "teahouse",
    title: "Tea Time",
    category: "food",
    words: [
      { word: "KETTLE", clue: "Boils the water first" },
      { word: "LEAVES", clue: "Steeped to make the drink" },
      { word: "STEEP", clue: "Let the tea sit and brew" },
      { word: "CUP", clue: "Where the tea ends up" },
      { word: "GINGER", clue: "Spicy addition to a warming brew" },
      { word: "HONEY", clue: "A sweet stir-in" },
      { word: "SAUCER", clue: "Sits underneath the cup" },
      { word: "BREW", clue: "The steeped result" },
      { word: "STEAM", clue: "Rises off a fresh cup" },
      { word: "SIP", clue: "How you drink it slowly" },
    ],
  },
  {
    id: "spaceflight",
    title: "Liftoff",
    category: "science",
    words: [
      { word: "ROCKET", clue: "Vehicle that leaves the atmosphere" },
      { word: "LAUNCH", clue: "The moment of liftoff" },
      { word: "ORBIT", clue: "The circular path around a planet" },
      { word: "CREW", clue: "The astronauts on board" },
      { word: "STATION", clue: "A permanent outpost in orbit" },
      { word: "FUEL", clue: "What powers the engines" },
      { word: "GRAVITY", clue: "What a rocket fights to escape" },
      { word: "SHUTTLE", clue: "A reusable spacecraft" },
      { word: "SATELLITE", clue: "Orbits a planet, often man-made" },
      { word: "COUNTDOWN", clue: "Ten, nine, eight..." },
    ],
  },
  {
    id: "autumnleaves",
    title: "Autumn Leaves",
    category: "nature",
    words: [
      { word: "HARVEST", clue: "Gathering the season's crops" },
      { word: "MAPLE", clue: "Tree famous for turning red" },
      { word: "CRISP", clue: "How the air feels in autumn" },
      { word: "PUMPKIN", clue: "Orange fruit of the season" },
      { word: "ACORN", clue: "Falls from an oak in autumn" },
      { word: "SWEATER", clue: "What you dig out of the closet" },
      { word: "RAKE", clue: "Used to gather fallen leaves" },
      { word: "AMBER", clue: "A warm autumn leaf color" },
      { word: "ORCHARD", clue: "Where you go apple-picking" },
      { word: "BREEZE", clue: "Sends the leaves spinning down" },
    ],
  },
  {
    id: "marketday",
    title: "Market Day",
    category: "world_culture",
    words: [
      { word: "STALL", clue: "A vendor's small setup" },
      { word: "VENDOR", clue: "The person selling the goods" },
      { word: "BARGAIN", clue: "A good deal, or the act of negotiating one" },
      { word: "BASKET", clue: "Carries the day's purchases" },
      { word: "CROWD", clue: "What fills a market by mid-morning" },
      { word: "AISLE", clue: "The path between the stalls" },
      { word: "COIN", clue: "Old-fashioned way to pay" },
      { word: "SPICE", clue: "Sold loose, by weight and smell" },
      { word: "CRATE", clue: "Holds the produce before it's unpacked" },
      { word: "SCALE", clue: "Weighs out the produce" },
    ],
  },
  {
    id: "letters",
    title: "By Post",
    category: "literature",
    words: [
      { word: "ENVELOPE", clue: "Holds the letter inside" },
      { word: "STAMP", clue: "Pays for the journey" },
      { word: "POSTCARD", clue: "A short note, no envelope needed" },
      { word: "ADDRESS", clue: "Tells the letter where to go" },
      { word: "INK", clue: "What a pen writes with" },
      { word: "SEAL", clue: "Closes the envelope shut" },
      { word: "MAILBOX", clue: "Where the letter waits to be found" },
      { word: "SIGNATURE", clue: "How you sign off" },
      { word: "PARCEL", clue: "A package sent by post" },
      { word: "PEN", clue: "The letter-writer's tool" },
    ],
  },
  {
    id: "chessboard",
    title: "Chessboard",
    category: "design",
    words: [
      { word: "PAWN", clue: "The most numerous piece" },
      { word: "KNIGHT", clue: "Moves in an L shape" },
      { word: "BISHOP", clue: "Moves only along diagonals" },
      { word: "CASTLE", clue: "Slang for the rook" },
      { word: "QUEEN", clue: "The most powerful piece on the board" },
      { word: "CHECK", clue: "The king is under threat" },
      { word: "BOARD", clue: "Sixty-four squares, alternating color" },
      { word: "MOVE", clue: "What each player takes turns making" },
      { word: "OPENING", clue: "The game's first few moves" },
      { word: "MATE", clue: "Short for the winning move" },
    ],
  },
];
