import { WordClue } from "./crosswordGen";

export interface CrosswordTheme {
  id: string;
  title: string;
  category: string;
  words: WordClue[];
}

export const CROSSWORD_THEMES: CrosswordTheme[] = [
  {
    id: "morning",
    title: "Morning Routine",
    category: "food",
    words: [
      { word: "TOAST", clue: "Breakfast slice, often buttered" },
      { word: "ALARM", clue: "Wakes you up, rudely" },
      { word: "MUG", clue: "Holds your coffee" },
      { word: "SUNRISE", clue: "Dawn's arrival" },
      { word: "STRETCH", clue: "Do this before getting out of bed" },
      { word: "SHOWER", clue: "Morning rinse" },
      { word: "ROUTE", clue: "Your path to work" },
      { word: "TEA", clue: "Kettle's usual purpose" },
      { word: "YAWN", clue: "Involuntary morning gesture" },
      { word: "RISE", clue: "Get up, as the sun does" },
    ],
  },
  {
    id: "ocean",
    title: "By the Sea",
    category: "nature",
    words: [
      { word: "WAVE", clue: "Rolls onto the shore" },
      { word: "SHELL", clue: "Home for a hermit crab" },
      { word: "TIDE", clue: "Rises and falls twice daily" },
      { word: "CORAL", clue: "Builds colorful reefs" },
      { word: "ANCHOR", clue: "Keeps a boat in place" },
      { word: "SAND", clue: "Beach's main ingredient" },
      { word: "CRAB", clue: "Walks sideways" },
      { word: "PIER", clue: "Walkway out over the water" },
      { word: "SALT", clue: "Makes the sea taste the way it does" },
      { word: "GULL", clue: "Beach bird known for stealing chips" },
    ],
  },
  {
    id: "kitchen",
    title: "In the Kitchen",
    category: "food",
    words: [
      { word: "WHISK", clue: "For beating eggs" },
      { word: "OVEN", clue: "Bakes your bread" },
      { word: "SPICE", clue: "Cinnamon or cumin, for one" },
      { word: "LADLE", clue: "Serves the soup" },
      { word: "KNIFE", clue: "Chops the vegetables" },
      { word: "SIMMER", clue: "Gentle cooking heat, below a boil" },
      { word: "TOAST", clue: "Browns bread in a toaster" },
      { word: "APRON", clue: "Protects your clothes while cooking" },
      { word: "STIR", clue: "Move a spoon around a pot" },
      { word: "PAN", clue: "Frying vessel" },
    ],
  },
  {
    id: "garden",
    title: "In the Garden",
    category: "nature",
    words: [
      { word: "ROSE", clue: "Thorny, fragrant flower" },
      { word: "SOIL", clue: "What roots grow in" },
      { word: "SPADE", clue: "Digs a hole" },
      { word: "SEED", clue: "Grows into a plant" },
      { word: "PETAL", clue: "Part of a flower" },
      { word: "BLOOM", clue: "To flower" },
      { word: "SHADE", clue: "Where ferns prefer to grow" },
      { word: "WATER", clue: "Plants need this to grow" },
      { word: "LEAF", clue: "Green part of a plant" },
      { word: "VINE", clue: "Climbing plant" },
    ],
  },
  {
    id: "music",
    title: "A Little Music",
    category: "music",
    words: [
      { word: "PIANO", clue: "88 keys, black and white" },
      { word: "TEMPO", clue: "Speed of a piece of music" },
      { word: "CHORD", clue: "Three or more notes together" },
      { word: "VIOLIN", clue: "Bowed string instrument" },
      { word: "SONG", clue: "A tune with words" },
      { word: "NOTE", clue: "A single musical sound" },
      { word: "DRUM", clue: "You hit this to keep the beat" },
      { word: "STAGE", clue: "Where performers stand" },
      { word: "RHYTHM", clue: "The music's pulse" },
      { word: "ENCORE", clue: "Audience shout for one more song" },
    ],
  },
  {
    id: "weather",
    title: "Weather Watch",
    category: "nature",
    words: [
      { word: "CLOUD", clue: "Floats in the sky, holds rain" },
      { word: "STORM", clue: "Thunder and lightning event" },
      { word: "BREEZE", clue: "A gentle wind" },
      { word: "FROST", clue: "Thin ice on the morning grass" },
      { word: "RAINBOW", clue: "Arc of color after rain" },
      { word: "MIST", clue: "Light, low-lying fog" },
      { word: "SNOW", clue: "Falls in soft white flakes" },
      { word: "HUMID", clue: "Sticky, moisture-heavy air" },
      { word: "SUNNY", clue: "Clear-sky weather" },
      { word: "GALE", clue: "A very strong wind" },
    ],
  },
  {
    id: "travel",
    title: "Getting Away",
    category: "travel",
    words: [
      { word: "TICKET", clue: "You need one to board" },
      { word: "MAP", clue: "Helps you find your way" },
      { word: "TRAIN", clue: "Rides on rails" },
      { word: "HOSTEL", clue: "Budget place to sleep" },
      { word: "PASSPORT", clue: "Your ID for crossing borders" },
      { word: "LUGGAGE", clue: "What you pack and haul around" },
      { word: "TRAIL", clue: "Path through the woods" },
      { word: "GUIDE", clue: "Leads a tour" },
      { word: "COMPASS", clue: "Always points north" },
      { word: "VISA", clue: "Permission to enter a country" },
    ],
  },
  {
    id: "reading",
    title: "Bookish",
    category: "books",
    words: [
      { word: "NOVEL", clue: "A long work of fiction" },
      { word: "CHAPTER", clue: "A section of a book" },
      { word: "PLOT", clue: "What happens in a story" },
      { word: "AUTHOR", clue: "Wrote the book" },
      { word: "SPINE", clue: "The book's backbone on the shelf" },
      { word: "VERSE", clue: "A line of poetry" },
      { word: "PAGE", clue: "One side of a leaf in a book" },
      { word: "LIBRARY", clue: "Full of borrowed books" },
      { word: "MARGIN", clue: "Where you scribble notes" },
      { word: "READER", clue: "Someone turning these very pages" },
    ],
  },
  {
    id: "sports",
    title: "Game Day",
    category: "sports",
    words: [
      { word: "GOAL", clue: "What a striker is aiming for" },
      { word: "COURT", clue: "Where basketball is played" },
      { word: "REFEREE", clue: "Blows the whistle" },
      { word: "SERVE", clue: "Starts a point in tennis" },
      { word: "MEDAL", clue: "Podium reward" },
      { word: "SPRINT", clue: "A short, fast race" },
      { word: "COACH", clue: "Trains the team" },
      { word: "STADIUM", clue: "Where the crowd gathers" },
      { word: "RACKET", clue: "Swung in tennis or badminton" },
      { word: "JERSEY", clue: "Team shirt with a number" },
    ],
  },
  {
    id: "museum",
    title: "At the Museum",
    category: "art",
    words: [
      { word: "CANVAS", clue: "What a painter paints on" },
      { word: "SKETCH", clue: "A quick, rough drawing" },
      { word: "EASEL", clue: "Holds the canvas upright" },
      { word: "GALLERY", clue: "Room full of art" },
      { word: "PALETTE", clue: "Where paint colors are mixed" },
      { word: "FRESCO", clue: "Painted straight onto wet plaster" },
      { word: "SCULPTOR", clue: "Carves or molds a statue" },
      { word: "MURAL", clue: "A painting on a wall" },
      { word: "HUE", clue: "Another word for a color" },
      { word: "FRAME", clue: "Borders a painting" },
    ],
  },
  {
    id: "nightsky",
    title: "Night Sky",
    category: "science",
    words: [
      { word: "COMET", clue: "Icy visitor with a tail" },
      { word: "ORBIT", clue: "A planet's path around the sun" },
      { word: "GALAXY", clue: "A vast collection of stars" },
      { word: "TELESCOPE", clue: "Brings distant stars closer" },
      { word: "ECLIPSE", clue: "When one body blocks another's light" },
      { word: "NEBULA", clue: "A cloud of gas and dust in space" },
      { word: "METEOR", clue: "A shooting star" },
      { word: "LUNAR", clue: "Relating to the moon" },
      { word: "ASTEROID", clue: "A rocky body orbiting the sun" },
      { word: "GRAVITY", clue: "Keeps your feet on the ground" },
    ],
  },
  {
    id: "mountains",
    title: "High Ground",
    category: "nature",
    words: [
      { word: "SUMMIT", clue: "The very top of a peak" },
      { word: "RIDGE", clue: "A long, narrow mountain crest" },
      { word: "GLACIER", clue: "A slow-moving river of ice" },
      { word: "ALTITUDE", clue: "Height above sea level" },
      { word: "TRAIL", clue: "The path you hike up" },
      { word: "PEAK", clue: "Another word for a mountain's top" },
      { word: "BOULDER", clue: "A large loose rock" },
      { word: "SLOPE", clue: "The mountain's angled side" },
      { word: "ECHO", clue: "What comes back when you shout in a valley" },
      { word: "CLIFF", clue: "A steep rock face" },
    ],
  },
  {
    id: "cinema",
    title: "At the Movies",
    category: "film",
    words: [
      { word: "SCREEN", clue: "Where the picture is projected" },
      { word: "DIRECTOR", clue: "Calls the shots on set" },
      { word: "SCRIPT", clue: "The written dialogue and story" },
      { word: "TRAILER", clue: "A short preview of what's coming" },
      { word: "SEQUEL", clue: "Part two of the story" },
      { word: "CAMEO", clue: "A brief, notable appearance" },
      { word: "POPCORN", clue: "The classic theater snack" },
      { word: "CREDITS", clue: "Rolls at the very end" },
      { word: "PLOT", clue: "What actually happens in the story" },
      { word: "ACTOR", clue: "Plays a role on screen" },
    ],
  },
  {
    id: "bakery",
    title: "At the Bakery",
    category: "food",
    words: [
      { word: "DOUGH", clue: "What you knead before it bakes" },
      { word: "YEAST", clue: "Makes bread rise" },
      { word: "CRUST", clue: "The bread's outer layer" },
      { word: "FLOUR", clue: "Bakery's most basic ingredient" },
      { word: "OVEN", clue: "Where the baking happens" },
      { word: "ICING", clue: "Sweet topping on a cake" },
      { word: "LOAF", clue: "A whole baked bread, uncut" },
      { word: "PASTRY", clue: "Flaky baked good, often filled" },
      { word: "RECIPE", clue: "Instructions for a dish" },
      { word: "KNEAD", clue: "Work the dough by hand" },
    ],
  },
  {
    id: "mindscape",
    title: "A Wandering Mind",
    category: "philosophy",
    words: [
      { word: "REASON", clue: "Logical thinking, roughly" },
      { word: "DOUBT", clue: "The opposite of certainty" },
      { word: "ETHICS", clue: "The study of right and wrong" },
      { word: "MEANING", clue: "What you're searching for, existentially" },
      { word: "IDEA", clue: "A single thought, distilled" },
      { word: "LOGIC", clue: "Step-by-step reasoning" },
      { word: "TRUTH", clue: "What philosophers argue endlessly about" },
      { word: "MIND", clue: "Where thoughts happen" },
      { word: "VALUE", clue: "What you believe matters" },
      { word: "SELF", clue: "The \"who\" behind your thoughts" },
    ],
  },
  {
    id: "festival",
    title: "Festival Lights",
    category: "indian_culture",
    words: [
      { word: "LANTERN", clue: "Lit and hung to mark a celebration" },
      { word: "SWEETS", clue: "Shared generously during a festival" },
      { word: "RANGOLI", clue: "Colorful floor pattern made for celebrations" },
      { word: "DIYA", clue: "A small oil lamp" },
      { word: "MEHNDI", clue: "Henna design on the hands" },
      { word: "DRUM", clue: "Instrument that leads a festival procession" },
      { word: "FEAST", clue: "A large shared celebratory meal" },
      { word: "GUEST", clue: "Someone you welcome for the occasion" },
      { word: "DANCE", clue: "What the courtyard fills with, come evening" },
      { word: "COLOR", clue: "Thrown, worn, or painted to celebrate" },
    ],
  },
  {
    id: "globaltable",
    title: "Around the Table",
    category: "world_culture",
    words: [
      { word: "SPICE", clue: "What travels furthest in a suitcase, smell-wise" },
      { word: "NOODLE", clue: "Long strand, many countries claim a version" },
      { word: "MARKET", clue: "Where the day's ingredients get chosen" },
      { word: "CUSTOM", clue: "A tradition passed down, unwritten" },
      { word: "FEAST", clue: "A meal that takes all day to make" },
      { word: "RECIPE", clue: "A grandmother's, usually undocumented" },
      { word: "TEA", clue: "Ritual drink, wildly different by country" },
      { word: "SPOON", clue: "Not every culture eats with one" },
      { word: "TOAST", clue: "What you raise before a shared meal" },
      { word: "GUEST", clue: "Treated as an honor to host" },
    ],
  },
  {
    id: "camera",
    title: "Through the Lens",
    category: "art",
    words: [
      { word: "SHUTTER", clue: "Opens and closes to let light in" },
      { word: "FOCUS", clue: "Sharpens the image" },
      { word: "APERTURE", clue: "Controls how much light enters" },
      { word: "EXPOSURE", clue: "How long the film or sensor is lit" },
      { word: "FRAME", clue: "What's included in the shot" },
      { word: "LENS", clue: "Bends the light into an image" },
      { word: "FILM", clue: "The old way of capturing light" },
      { word: "ZOOM", clue: "Get closer without moving your feet" },
      { word: "FLASH", clue: "A burst of extra light" },
      { word: "PRINT", clue: "The photo, made physical" },
    ],
  },
  {
    id: "forestwalk",
    title: "Into the Woods",
    category: "nature",
    words: [
      { word: "CANOPY", clue: "The forest's leafy ceiling" },
      { word: "MOSS", clue: "Soft green growth on old bark" },
      { word: "TRUNK", clue: "A tree's main stem" },
      { word: "FERN", clue: "Feathery plant that loves shade" },
      { word: "TRAIL", clue: "The path through the trees" },
      { word: "ROOTS", clue: "Anchor a tree underground" },
      { word: "BARK", clue: "A tree's outer skin" },
      { word: "CLEARING", clue: "A sudden open patch of light" },
      { word: "ACORN", clue: "An oak tree's seed" },
      { word: "OWL", clue: "The forest's night-shift hunter" },
    ],
  },
  {
    id: "rainyday",
    title: "Rainy Day",
    category: "nature",
    words: [
      { word: "PUDDLE", clue: "Small pool left behind by rain" },
      { word: "UMBRELLA", clue: "Keeps you dry, mostly" },
      { word: "DRIZZLE", clue: "Light, gentle rain" },
      { word: "THUNDER", clue: "The sound that follows lightning" },
      { word: "DOWNPOUR", clue: "Rain that means business" },
      { word: "RAINCOAT", clue: "Waterproof jacket for the occasion" },
      { word: "GUTTER", clue: "Channels rainwater off a roof" },
      { word: "SPLASH", clue: "What a puddle does underfoot" },
      { word: "DAMP", clue: "Not quite dry" },
      { word: "STORM", clue: "Rain with attitude" },
    ],
  },
  {
    id: "teahouse",
    title: "Tea Time",
    category: "food",
    words: [
      { word: "KETTLE", clue: "Boils the water first" },
      { word: "LEAVES", clue: "Steeped to make the drink" },
      { word: "STEEP", clue: "Let the tea sit and brew" },
      { word: "CUP", clue: "Where the tea ends up" },
      { word: "GINGER", clue: "Spicy addition to a warming brew" },
      { word: "HONEY", clue: "A sweet stir-in" },
      { word: "SAUCER", clue: "Sits underneath the cup" },
      { word: "BREW", clue: "The steeped result" },
      { word: "STEAM", clue: "Rises off a fresh cup" },
      { word: "SIP", clue: "How you drink it slowly" },
    ],
  },
  {
    id: "spaceflight",
    title: "Liftoff",
    category: "science",
    words: [
      { word: "ROCKET", clue: "Vehicle that leaves the atmosphere" },
      { word: "LAUNCH", clue: "The moment of liftoff" },
      { word: "ORBIT", clue: "The circular path around a planet" },
      { word: "CREW", clue: "The astronauts on board" },
      { word: "STATION", clue: "A permanent outpost in orbit" },
      { word: "FUEL", clue: "What powers the engines" },
      { word: "GRAVITY", clue: "What a rocket fights to escape" },
      { word: "SHUTTLE", clue: "A reusable spacecraft" },
      { word: "SATELLITE", clue: "Orbits a planet, often man-made" },
      { word: "COUNTDOWN", clue: "Ten, nine, eight..." },
    ],
  },
  {
    id: "autumnleaves",
    title: "Autumn Leaves",
    category: "nature",
    words: [
      { word: "HARVEST", clue: "Gathering the season's crops" },
      { word: "MAPLE", clue: "Tree famous for turning red" },
      { word: "CRISP", clue: "How the air feels in autumn" },
      { word: "PUMPKIN", clue: "Orange fruit of the season" },
      { word: "ACORN", clue: "Falls from an oak in autumn" },
      { word: "SWEATER", clue: "What you dig out of the closet" },
      { word: "RAKE", clue: "Used to gather fallen leaves" },
      { word: "AMBER", clue: "A warm autumn leaf color" },
      { word: "ORCHARD", clue: "Where you go apple-picking" },
      { word: "BREEZE", clue: "Sends the leaves spinning down" },
    ],
  },
  {
    id: "marketday",
    title: "Market Day",
    category: "world_culture",
    words: [
      { word: "STALL", clue: "A vendor's small setup" },
      { word: "VENDOR", clue: "The person selling the goods" },
      { word: "BARGAIN", clue: "A good deal, or the act of negotiating one" },
      { word: "BASKET", clue: "Carries the day's purchases" },
      { word: "CROWD", clue: "What fills a market by mid-morning" },
      { word: "AISLE", clue: "The path between the stalls" },
      { word: "COIN", clue: "Old-fashioned way to pay" },
      { word: "SPICE", clue: "Sold loose, by weight and smell" },
      { word: "CRATE", clue: "Holds the produce before it's unpacked" },
      { word: "SCALE", clue: "Weighs out the produce" },
    ],
  },
  {
    id: "letters",
    title: "By Post",
    category: "literature",
    words: [
      { word: "ENVELOPE", clue: "Holds the letter inside" },
      { word: "STAMP", clue: "Pays for the journey" },
      { word: "POSTCARD", clue: "A short note, no envelope needed" },
      { word: "ADDRESS", clue: "Tells the letter where to go" },
      { word: "INK", clue: "What a pen writes with" },
      { word: "SEAL", clue: "Closes the envelope shut" },
      { word: "MAILBOX", clue: "Where the letter waits to be found" },
      { word: "SIGNATURE", clue: "How you sign off" },
      { word: "PARCEL", clue: "A package sent by post" },
      { word: "PEN", clue: "The letter-writer's tool" },
    ],
  },
  {
    id: "chessboard",
    title: "Chessboard",
    category: "design",
    words: [
      { word: "PAWN", clue: "The most numerous piece" },
      { word: "KNIGHT", clue: "Moves in an L shape" },
      { word: "BISHOP", clue: "Moves only along diagonals" },
      { word: "CASTLE", clue: "Slang for the rook" },
      { word: "QUEEN", clue: "The most powerful piece on the board" },
      { word: "CHECK", clue: "The king is under threat" },
      { word: "BOARD", clue: "Sixty-four squares, alternating color" },
      { word: "MOVE", clue: "What each player takes turns making" },
      { word: "OPENING", clue: "The game's first few moves" },
      { word: "MATE", clue: "Short for the winning move" },
    ],
  },
  // The 16 below were added together as a deliberately harder batch —
  // indirect, fact-based, or figurative clues rather than the
  // dictionary-definition style above — and leaning into categories (per
  // lib/sectionInterests.ts's InterestTag taxonomy) the original 26 barely
  // touched: history, technology, architecture, psychology, and poetry get
  // two apiece; science, design, philosophy, film, world_culture, and art
  // each get one more on fresh ground. Each bank was run through
  // generateBestCrossword before being added — all place 10-11 of 11 words.
  {
    id: "revolutions",
    title: "Turning Points",
    category: "history",
    words: [
      { word: "TREATY", clue: "Versailles produced one, in 1919" },
      { word: "EMPIRE", clue: "What Rome, the Ottomans, and the Mongols all were, at their peak" },
      { word: "DYNASTY", clue: "Ming or Tudor, for instance" },
      { word: "REBEL", clue: "One who refuses the crown's authority" },
      { word: "COLONY", clue: "A territory ruled from somewhere else entirely" },
      { word: "EXILE", clue: "Napoleon's fate, twice" },
      { word: "ARCHIVE", clue: "Where the old decrees are kept" },
      { word: "CONQUEST", clue: "William's claim to England, 1066" },
      { word: "RELIC", clue: "A fragment the museum dates by" },
      { word: "CENSUS", clue: "A count the Romans took every five years" },
      { word: "REGIME", clue: "The government of the day, often the one that gets toppled" },
    ],
  },
  {
    id: "coldwar",
    title: "Behind the Curtain",
    category: "history",
    words: [
      { word: "ESPIONAGE", clue: "The business of double agents" },
      { word: "BLOCKADE", clue: "Berlin's, in 1948" },
      { word: "DEFECTOR", clue: "One who crosses to the other side for good" },
      { word: "SATELLITE", clue: "A state controlled from Moscow, loosely speaking" },
      { word: "ARMISTICE", clue: "A pause in fighting, not quite peace" },
      { word: "BUNKER", clue: "Built to survive what the sirens warned of" },
      { word: "CIPHER", clue: "What a code clerk spends all day decoding" },
      { word: "CURTAIN", clue: "What Churchill said fell across Europe" },
      { word: "STALEMATE", clue: "Neither side advancing, neither retreating" },
      { word: "WARHEAD", clue: "The business end of a missile" },
      { word: "ALLIANCE", clue: "NATO, from the West's side of it" },
    ],
  },
  {
    id: "circuitry",
    title: "Under the Hood",
    category: "technology",
    words: [
      { word: "FIRMWARE", clue: "Software baked straight into the hardware" },
      { word: "LATENCY", clue: "The lag between a click and a response" },
      { word: "ENCRYPT", clue: "Scramble a message so only the right key opens it" },
      { word: "BANDWIDTH", clue: "How much data can move at once" },
      { word: "PROTOCOL", clue: "The agreed-upon rules two machines talk by" },
      { word: "KERNEL", clue: "The operating system's innermost core" },
      { word: "CACHE", clue: "Fast, temporary storage kept close at hand" },
      { word: "BUFFER", clue: "Holds data briefly before it's used" },
      { word: "ROUTER", clue: "Directs traffic between networks" },
      { word: "BINARY", clue: "A system built from just two digits" },
      { word: "PATCH", clue: "A small fix shipped after launch" },
    ],
  },
  {
    id: "startup",
    title: "The Pitch",
    category: "technology",
    words: [
      { word: "EQUITY", clue: "A stake in the company, not cash" },
      { word: "RUNWAY", clue: "How long the money lasts before it runs out" },
      { word: "PIVOT", clue: "A sudden change of business direction" },
      { word: "VALUATION", clue: "What investors think the company is worth, on paper" },
      { word: "DISRUPT", clue: "Upend an industry's old way of doing things" },
      { word: "INCUBATOR", clue: "Where very young companies are nurtured" },
      { word: "UNICORN", clue: "A startup worth a billion, informally" },
      { word: "BURN", clue: "How fast the cash disappears, for short" },
      { word: "FOUNDER", clue: "Started the company, usually still runs it" },
      { word: "SCALE", clue: "Grow without breaking, ideally" },
      { word: "ANGEL", clue: "An early investor, often acting alone" },
    ],
  },
  {
    id: "blueprint",
    title: "Load-Bearing",
    category: "architecture",
    words: [
      { word: "CANTILEVER", clue: "A beam supported at only one end" },
      { word: "FACADE", clue: "A building's face, not necessarily its truth" },
      { word: "TRUSS", clue: "A triangular framework that bears a load" },
      { word: "MASONRY", clue: "Stonework or brickwork, broadly" },
      { word: "ATRIUM", clue: "An open central court, often skylit" },
      { word: "PARAPET", clue: "A low wall at a roof's edge" },
      { word: "COLONNADE", clue: "A row of evenly spaced columns" },
      { word: "VAULT", clue: "An arched ceiling — or where the valuables sleep" },
      { word: "MORTAR", clue: "Binds the bricks together" },
      { word: "SPAN", clue: "The distance a bridge covers unsupported" },
      { word: "FOOTING", clue: "What a foundation literally rests on" },
    ],
  },
  {
    id: "citybuilt",
    title: "City Plan",
    category: "architecture",
    words: [
      { word: "ZONING", clue: "Rules for what can be built where" },
      { word: "SKYLINE", clue: "A city's silhouette against the sky" },
      { word: "CORRIDOR", clue: "A long connecting passage, or a transit route" },
      { word: "EASEMENT", clue: "A legal right to use someone else's land" },
      { word: "GENTRIFY", clue: "To upscale a neighborhood, often pricing out its own" },
      { word: "BOULEVARD", clue: "A broad, tree-lined avenue" },
      { word: "ALLEY", clue: "A narrow passage between buildings" },
      { word: "PLAZA", clue: "An open public square" },
      { word: "TRANSIT", clue: "How a city moves its people" },
      { word: "DENSITY", clue: "How tightly a city is packed" },
      { word: "SPRAWL", clue: "Unchecked outward growth of a city" },
    ],
  },
  {
    id: "mindgames",
    title: "The Thinking Mind",
    category: "psychology",
    words: [
      { word: "COGNITION", clue: "Mental processes like thinking and knowing, together" },
      { word: "BIAS", clue: "A thumb quietly resting on the scale of judgment" },
      { word: "EMPATHY", clue: "Feeling what someone else feels, not just understanding it" },
      { word: "DENIAL", clue: "Refusing to accept an uncomfortable truth" },
      { word: "TRAUMA", clue: "A wound the mind carries, not the body" },
      { word: "INSTINCT", clue: "A reaction that skips conscious thought entirely" },
      { word: "THERAPY", clue: "Structured conversation meant to heal" },
      { word: "MEMORY", clue: "Not a recording — more a reconstruction" },
      { word: "ANXIETY", clue: "Worry that's outrun its original purpose" },
      { word: "STIMULUS", clue: "Whatever triggers a response" },
      { word: "REFLEX", clue: "An automatic, unlearned reaction" },
    ],
  },
  {
    id: "dreamstate",
    title: "Asleep At Last",
    category: "psychology",
    words: [
      { word: "INSOMNIA", clue: "The inability to fall, or stay, asleep" },
      { word: "PSYCHE", clue: "The mind, in the Freudian sense" },
      { word: "NIGHTMARE", clue: "A dream that wakes you up sweating" },
      { word: "LUCID", clue: "Aware you're dreaming, while still dreaming" },
      { word: "REM", clue: "The sleep stage where dreaming mostly happens, for short" },
      { word: "FATIGUE", clue: "Exhaustion a nap won't quite fix" },
      { word: "HYPNOSIS", clue: "A trance state used to access the subconscious" },
      { word: "SLUMBER", clue: "A poetic word for sleep" },
      { word: "DROWSY", clue: "Fighting to keep your eyes open" },
      { word: "AWAKEN", clue: "To stir out of sleep" },
      { word: "SNORE", clue: "The sound of a deep sleeper" },
    ],
  },
  {
    id: "versecraft",
    title: "Verse Craft",
    category: "poetry",
    words: [
      { word: "METAPHOR", clue: "A comparison that drops the word “like”" },
      { word: "STANZA", clue: "A poem's paragraph, essentially" },
      { word: "SONNET", clue: "Fourteen lines, strict rhyme" },
      { word: "METER", clue: "The rhythmic pulse beneath the words" },
      { word: "ENJAMBMENT", clue: "A sentence spilling past the end of its line" },
      { word: "COUPLET", clue: "Two rhyming lines in a row" },
      { word: "RHYME", clue: "What “moon” and “June” famously do" },
      { word: "ELEGY", clue: "A poem mourning the dead" },
      { word: "ODE", clue: "A poem written in praise of something" },
      { word: "IMAGERY", clue: "Language that paints a picture in the mind" },
      { word: "VERSE", clue: "A single line of poetry, loosely" },
    ],
  },
  {
    id: "oldpoets",
    title: "Dead Poets",
    category: "poetry",
    words: [
      { word: "HAIKU", clue: "Seventeen syllables, three lines" },
      { word: "BALLAD", clue: "A narrative poem, often sung" },
      { word: "LIMERICK", clue: "Five lines, usually comic, strict rhythm" },
      { word: "EPIC", clue: "A long poem recounting a hero's deeds" },
      { word: "BARD", clue: "An old word for a poet, especially a Celtic one" },
      { word: "MUSE", clue: "The source of a poet's inspiration, in myth" },
      { word: "QUATRAIN", clue: "A four-line stanza" },
      { word: "LYRIC", clue: "Poetry meant to express personal feeling" },
      { word: "PROSODY", clue: "The study of a poem's rhythm and sound" },
      { word: "REFRAIN", clue: "A line repeated throughout a poem or song" },
      { word: "CANTO", clue: "A division of a long poem, like Dante's" },
    ],
  },
  {
    id: "labwork",
    title: "In the Lab",
    category: "science",
    words: [
      { word: "HYPOTHESIS", clue: "An educated guess, waiting to be tested" },
      { word: "CATALYST", clue: "Speeds up a reaction without being used up itself" },
      { word: "ENZYME", clue: "A biological catalyst, essentially" },
      { word: "PIPETTE", clue: "Measures out a precise, small volume of liquid" },
      { word: "VARIABLE", clue: "The one thing you deliberately change in an experiment" },
      { word: "CONTROL", clue: "The group that gets no treatment, for comparison" },
      { word: "SOLUTE", clue: "The thing being dissolved" },
      { word: "REAGENT", clue: "A substance added to trigger a reaction" },
      { word: "RESIDUE", clue: "What's left behind once a reaction settles" },
      { word: "TITRATION", clue: "Gradually adding one solution to another to find a concentration" },
      { word: "OSMOSIS", clue: "Movement of water across a membrane, passively" },
    ],
  },
  {
    id: "colortheory",
    title: "Color Theory",
    category: "design",
    words: [
      { word: "HUE", clue: "A color's position on the wheel, essentially" },
      { word: "SATURATION", clue: "How intense or washed-out a color is" },
      { word: "CONTRAST", clue: "The difference that makes elements stand apart" },
      { word: "GRADIENT", clue: "A smooth blend from one color into another" },
      { word: "PALETTE", clue: "The set of colors a design sticks to" },
      { word: "TINT", clue: "A color lightened with white" },
      { word: "SHADE", clue: "A color darkened with black" },
      { word: "COMPLEMENT", clue: "A color directly across the wheel from another" },
      { word: "MONOCHROME", clue: "Built from a single hue's range" },
      { word: "HARMONY", clue: "Colors that simply work well together" },
      { word: "PIGMENT", clue: "The substance that actually gives paint its color" },
    ],
  },
  {
    id: "logicroom",
    title: "The Logic Room",
    category: "philosophy",
    words: [
      { word: "PREMISE", clue: "A statement an argument is built on" },
      { word: "FALLACY", clue: "A flaw in reasoning that still sounds convincing" },
      { word: "SYLLOGISM", clue: "A three-part logical argument, classically" },
      { word: "PARADOX", clue: "A statement that contradicts itself, yet seems true" },
      { word: "INFERENCE", clue: "A conclusion drawn from evidence, not stated outright" },
      { word: "AXIOM", clue: "A truth accepted without needing proof" },
      { word: "DIALECTIC", clue: "A method of argument through contradiction" },
      { word: "COHERENCE", clue: "When an argument's parts all hang together" },
      { word: "SKEPTIC", clue: "One who doubts by default" },
      { word: "VALIDITY", clue: "Whether an argument's logic actually holds" },
      { word: "REBUTTAL", clue: "A direct answer to someone else's argument" },
    ],
  },
  {
    id: "backlot",
    title: "Behind the Scenes",
    category: "film",
    words: [
      { word: "MONTAGE", clue: "A rapid sequence of shots condensing time" },
      { word: "FOLEY", clue: "Sound effects recreated artificially in post" },
      { word: "STORYBOARD", clue: "A comic-strip plan of the shots to come" },
      { word: "CONTINUITY", clue: "Keeping details consistent from shot to shot" },
      { word: "DOLLY", clue: "A wheeled platform the camera rides on" },
      { word: "GAFFER", clue: "The chief lighting technician on set" },
      { word: "WRAP", clue: "What's called when filming for the day is done" },
      { word: "CUT", clue: "The editor's basic unit of change" },
      { word: "ENSEMBLE", clue: "A cast without one single lead" },
      { word: "MAKEUP", clue: "Transforms an actor's face before the cameras roll" },
      { word: "RUSHES", clue: "Unedited footage reviewed the same day it's shot" },
    ],
  },
  {
    id: "silkroad",
    title: "Along the Silk Road",
    category: "world_culture",
    words: [
      { word: "CARAVAN", clue: "A group of traders crossing the desert together" },
      { word: "PORCELAIN", clue: "A fine Chinese export Europe tried for centuries to copy" },
      { word: "OASIS", clue: "A green stop in an otherwise empty desert" },
      { word: "BAZAAR", clue: "A sprawling marketplace, especially in the East" },
      { word: "NOMAD", clue: "One with no fixed home, by choice or necessity" },
      { word: "TARIFF", clue: "A tax levied on goods crossing a border" },
      { word: "SILK", clue: "The luxury fabric that gave the route its name" },
      { word: "MERCHANT", clue: "A trader by profession" },
      { word: "FRONTIER", clue: "The edge of known, settled territory" },
      { word: "DIASPORA", clue: "A people scattered far from their original home" },
      { word: "EMISSARY", clue: "A representative sent to negotiate on another's behalf" },
    ],
  },
  {
    id: "brushwork",
    title: "Brushwork",
    category: "art",
    words: [
      { word: "IMPASTO", clue: "Paint applied thickly enough to show the brushstroke" },
      { word: "GESSO", clue: "A primer coat applied before painting begins" },
      { word: "VANISHING", clue: "Where parallel lines appear to meet, in perspective" },
      { word: "CHIAROSCURO", clue: "Strong contrast between light and dark in a painting" },
      { word: "VARNISH", clue: "A protective coat brushed on once the paint has dried" },
      { word: "GLAZE", clue: "A thin, transparent layer brushed over dried paint" },
      { word: "STIPPLE", clue: "To paint using small dots or flecks" },
      { word: "LINEN", clue: "A traditional woven fabric used to stretch a canvas" },
      { word: "BLEND", clue: "To soften the line between two colors" },
      { word: "BRUSH", clue: "The tool that puts the paint where it's wanted" },
      { word: "BINDER", clue: "The substance that holds pigment particles together in paint" },
    ],
  },
];
